GorillaSwe/swipe-eats-frontend

src/App.tsx
src/lib/api/client.ts
src/lib/api/restaurants.ts
src/lib/api/test.ts

feat: Added the ability to display restaurant information obtained from the backend API

feat: Added the ability to display restaurant information

---

src/components/CardSwiper.tsx
src/components/ResultsPage.tsx
src/utils/api/restaurants.ts

[fix]選択したカテゴリーと距離が、検索条件に反映されなかったため修正

---

package-lock.json
package.json
src/components/CardSwiper.module.css
src/components/CardSwiper.tsx
src/components/StarRating.module.css
src/components/StarRating.tsx
src/styles/globals.css
src/types/RestaurantData.ts
yarn.lock

レストランのWebサイトなどの項目を追加表示するよう修正しました。

[add]レストラン情報の表示項目を増やしました。

---

src/app/map/page.module.css
src/app/map/page.tsx
src/app/results/page.tsx
src/features/map/components/RestaurantInfo.module.css
src/features/map/components/RestaurantInfo.tsx
src/features/map/components/RestaurantListItem.module.css
src/features/map/components/RestaurantListItem.tsx

右（like）にスワイプしたレストランをマップ画面で一覧表示にし、それを選択すると各レストランの詳細情報が表示されるようにしました。

[add]マップ画面でレストランの一覧を表示するようにしました。

---

src/app/globals.scss

検索結果画面でカードを右にスワイプした際に、overflowした箇所が見えなくなるよう修正

[add]検索結果画面でoverflowをhiddenにするよう修正

---

src/features/results/components/CardImageSlider.module.scss
src/features/results/components/CardImageSlider.tsx
src/features/results/components/CardSwiper.module.scss
src/features/results/components/CardSwiper.tsx

[add]検索結果ページのTinderCardにプログレスバーを追加

---

src/app/map/page.module.scss
src/app/map/page.tsx
src/features/map/components/Directions.tsx
src/features/map/components/RestaurantMarkers.module.scss
src/features/map/components/RestaurantMarkers.tsx
src/features/map/components/SelectedMarker.module.scss
src/features/map/components/SelectedMarker.tsx
src/features/map/components/UserMaker.tsx
src/features/map/components/UserMarker.module.scss
src/features/search/components/SortOptionSelector.tsx

[refactor]Map画面をリファクタリング

---

src/app/globals.scss
src/app/swipe/result/globals.scss
src/app/swipe/result/layout.tsx
src/components/ui/LoadingScreen.module.scss
src/features/results/components/CardButtons.module.scss
src/features/results/components/CardImageSlider.module.scss
src/features/results/components/CardSwiper.module.scss

layout.tsxをresult用に作成し、positionとoverflowを設定するよう修正しました

[add]検索結果画面でカードをスワイプした際にoverflowが働くよう修正

---

src/app/globals.scss
src/app/swipe/map/page.module.scss
src/app/swipe/result/page.module.scss
src/components/ui/LoadingScreen.module.scss
src/features/map/components/RestaurantInfo.module.scss
src/features/results/components/CardImageSlider.module.scss
src/features/results/components/CardSwiper.module.scss

モバイルで操作する際にツールバーなどを考慮してdvhを使用するよう修正

[refactor]vhを使用していた箇所をdvhを使用するよう修正

---

src/features/swipe/map/components/RestaurantInfo.tsx
src/features/swipe/result/components/CardInfo.tsx

fix:レストラン詳細の・を削除

---

src/app/profile/layout.scss
src/app/profile/layout.tsx
src/app/profile/page.module.scss
src/app/profile/page.tsx
src/app/swipe/result/globals.scss
src/components/ui/LoadingScreen.module.scss

feat:プロフィール画面 #60

---

src/app/profile/page.module.scss

refactor:profile画面をスマホ表示時文字サイズが小さい #79

---

src/app/profile/page.module.scss
src/app/profile/page.tsx
src/features/profile/components/RestaurantInfo.module.scss
src/features/profile/components/RestaurantInfo.tsx

feat:profile画面で各レストラン押下後画面 #81

---

src/app/profile/page.module.scss
src/app/profile/page.tsx
src/features/profile/components/RestaurantListItem.module.scss
src/features/profile/components/RestaurantListItem.tsx
src/features/profile/components/UserInfo.module.scss
src/features/profile/components/UserInfo.tsx

refactor:profile画面のコンポーネントをリファクタリング #86

---

src/features/profile/components/RestaurantInfo.module.scss
src/features/profile/components/RestaurantInfo.tsx

refactor:profile画面のレストラン詳細表示時、他を押すと非表示とする #88

---

src/app/profile/page.tsx
src/components/ui/LoginScreen.module.scss
src/components/ui/LoginScreen.tsx

feat:profile画面で非ログイン時の表示 #80

---

src/features/profile/components/RestaurantInfo.module.scss

refactor:profile画面、スマホ操作時縦が長い #97

---

src/app/profile/page.tsx
src/features/profile/components/RestaurantInfo.module.scss
src/features/profile/components/RestaurantInfo.tsx
src/types/RestaurantData.ts

feat:profile画面のレストラン詳細にお気に入り削除ボタン追加 #90

---

src/features/profile/components/RestaurantInfo.tsx
src/features/swipe/map/components/RestaurantInfo.tsx

feat:レストランのウェブサイトURLの表示をドメイン名のみとする #71

---

src/app/search/page.module.scss
src/app/search/page.tsx
src/features/search/components/RestaurantInfo.module.scss
src/features/search/components/RestaurantInfo.tsx
src/features/search/components/RestaurantListItem.module.scss
src/features/search/components/RestaurantListItem.tsx
src/types/RestaurantData.ts

feat:検索画面 #61

---

src/features/swipe/result/components/CardButtons.module.scss
src/features/swipe/result/components/CardButtons.tsx

feat:swipe/result画面のボタンを修正 #67

---

src/features/swipe/result/components/CardButtons.tsx
src/features/swipe/result/components/CardSwiper.tsx

feat:swipe/result画面にマップへ遷移ボタンを追加 #65

---

src/app/swipe/map/page.tsx
src/features/swipe/map/components/RestaurantInfo.module.scss
src/features/swipe/map/components/RestaurantInfo.tsx

feat:swipe/map画面でFavorite登録できるようにする #113

---

src/app/search/page.tsx

fix:本番環境でsearch処理時に海外のレストランが表示される #118

---

src/app/globals.scss
src/app/swipe/map/page.module.scss
src/features/swipe/map/components/RestaurantInfo.module.scss
src/features/swipe/map/components/RestaurantInfo.tsx

fix:swipe/map画面でスマホ操作時、Favorite削除のポップアップ表示z-indexが低い #117

---

src/app/profile/page.module.scss
src/app/profile/page.tsx
src/app/swipe/result/page.tsx
src/components/base/Error/ErrorScreen.module.scss
src/components/base/Error/ErrorScreen.tsx

feat:検索結果がない時などの表示修正 #128

---

src/features/swipe/search/hooks/useLocation.ts

fix:位置情報取得時、タイムアウトを待たずに値が設定されてしまう #130

---

src/app/profile/page.module.scss
src/app/profile/page.tsx
src/app/swipe/map/page.tsx
src/app/swipe/result/page.tsx
src/components/base/Error/ErrorScreen.tsx

feat:swipe/map画面で表示するレストランがない時の処理 #78

---

next.config.js
src/app/home/page.module.scss
src/app/home/page.tsx
src/app/profile/page.tsx
src/app/search/page.module.scss
src/app/search/page.tsx
src/app/swipe/map/page.module.scss
src/app/user/[userSub]/layout.scss
src/app/user/[userSub]/layout.tsx
src/app/user/[userSub]/page.tsx
src/features/profile/components/UserInfo.tsx
src/features/search/components/UserListItem.module.scss
src/features/search/components/UserListItem.tsx
src/features/user/components/UserInfo.module.scss
src/features/user/components/UserInfo.tsx
src/types/UserData.ts

feat:フォロー機能を実装 #141

---

src/app/user/[userSub]/page.tsx

fix:ユーザーのprofile画面のお気に入り数が取得できない #150

---

src/app/swipe/map/page.module.scss
src/app/swipe/map/page.tsx
src/features/swipe/map/components/RestaurantInfo.module.scss

feat:swipe/map画面をスマホ操作時、レストラン情報が広く表示されるよう修正 #153

---

src/app/swipe/map/page.module.scss

feat:swipe/map画面をスマホ操作時のレストラン情報表示をスムーズに修正 #156

---

src/app/swipe/map/page.module.scss
src/app/user/[userSub]/page.tsx

refactor:バックエンドのrefactorに合わせて修正 #158

---

src/app/profile/page.tsx

fix:未ログイン時にprofile画面でLoginSectionが表示されない #161

---

src/app/swipe/search/page.module.scss
src/app/swipe/search/page.tsx
src/features/swipe/search/components/AddressSearchDialog.module.scss
src/features/swipe/search/components/AddressSearchDialog.tsx
src/features/swipe/search/components/LocationSelector.module.scss
src/features/swipe/search/components/LocationSelector.tsx
src/features/swipe/search/components/PriceLevelSelector.tsx
src/lib/api/locationsInfo.ts
src/styles/mixins.scss

feat:swipe/search画面で検索地点を選択できるようにする #170

---

src/app/profile/page.tsx
src/app/swipe/result/page.tsx
src/components/base/RestaurantInfo/CommentDialog.module.scss
src/components/base/RestaurantInfo/CommentDialog.tsx
src/components/base/RestaurantInfo/RestaurantInfo.module.scss
src/components/base/RestaurantInfo/RestaurantInfo.tsx
src/components/ui/StarRating/UserStarRating.module.scss
src/components/ui/StarRating/UserStarRating.tsx
src/features/home/components/FavoriteInfo.module.scss
src/features/home/components/FavoriteInfo.tsx
src/features/swipe/map/components/RestaurantInfo.tsx
src/lib/api/favoritesInfo.ts
src/types/RestaurantData.ts

feat:Favoritesにratingとcommentを追加 #174

---

src/styles/UserProfilePage.module.scss

fix:お気に入りが1件の時、profile画面レイアウトが崩れる #176

---

src/components/base/RestaurantInfo/RestaurantInfo.tsx

fix:Search画面でお気に入り追加時にユーザー情報が表示されない #178

---

src/app/swipe/map/page.tsx
src/app/swipe/result/page.tsx
src/components/base/RestaurantInfo/RestaurantInfo.module.scss
src/components/base/RestaurantInfo/RestaurantInfo.tsx
src/features/home/components/FavoriteInfo.module.scss
src/features/home/components/FavoriteInfo.tsx
src/features/swipe/map/components/RestaurantInfo.module.scss
src/features/swipe/map/components/RestaurantInfo.tsx
src/features/swipe/map/components/RestaurantMarkers.tsx
src/features/swipe/result/components/CardSwiper.tsx
src/lib/api/restaurantsInfo.ts
src/types/RestaurantData.ts

feat:swipe/map画面でお気に入り情報追加時にユーザー情報を表示 #180

---

src/components/ui/StarRating/UserStarRating.tsx

feat:Favoriteのratingを0にできるように修正 #183

---

src/components/base/RestaurantListItemCard/RestaurantListItemCard.module.scss
src/components/base/RestaurantListItemCard/RestaurantListItemCard.tsx

feat:FavoriteのratingをRestaurantCardに表示 #185

---

src/components/base/RestaurantInfo/RestaurantInfo.module.scss
src/features/home/components/FavoriteInfo.module.scss
src/features/swipe/map/components/RestaurantInfo.module.scss

feat:commentの改行が反映されるよう修正 #187

---

src/components/base/RestaurantInfo/RestaurantInfo.tsx
src/features/swipe/map/components/RestaurantInfo.tsx

fix:swipe/map画面で再度お気に入り登録時にrating,commentが反映されない #190

---

src/app/profile/page.tsx
src/app/user/[userSub]/page.tsx
src/components/base/UserInfo/UserInfo.module.scss
src/components/base/UserInfo/UserInfo.tsx

feat:ユーザー情報の描画を修正 #195

---

src/app/followers/[userSub]/page.module.scss
src/app/followers/[userSub]/page.tsx
src/app/following/[userSub]/page.tsx
src/components/base/UserInfo/UserInfo.tsx
src/lib/api/followRelationshipsInfo.ts
src/styles/FollowPage.module.scss

feat:フォロワー、フォロー中用画面を作成 #197

---

src/app/home/page.tsx
src/lib/api/favoritesInfo.ts

feat:非ログイン時、Home画面でログインするよう修正 #199

---

__tests__/app/followers/[userSub]/page.test.tsx
__tests__/app/following/[userSub]/page.test.tsx
__tests__/app/home/page.test.tsx
__tests__/app/page.test.tsx
__tests__/app/profile/page.test.tsx
__tests__/app/search/page.test.tsx
__tests__/app/swipe/map/page.test.tsx
__tests__/app/swipe/result/page.test.tsx
__tests__/app/swipe/search/page.test.tsx
__tests__/app/user/[userSub]/page.test.tsx
jest.config.js
jest.setup.js
package-lock.json
package.json
src/app/home/page.tsx
src/app/user/[userSub]/page.tsx
src/components/base/Loading/LoadingSection.tsx
tsconfig.json
yarn.lock

feat:テストコードを実装 #202
